name: Test Linting
on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Test
        uses: ./
        with:
          path-to-sql-files: ./.github/workflows/test-sql-files
          file-name-filter: ShouldSucceed.sql
          path-to-lint-config: ./.github/config/.tsqllintrc