name: Test Linting
on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [16, 18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Test
        id: test
        uses: ./
        with:
          path-to-sql-files: ./.github/workflows/test-sql-files
          file-name-filter: ShouldSucceed.sql
          path-to-lint-config: ./.github/config/.tsqllintrc
      
      - name: Print Lint Result
        run: echo '${{ steps.test.outputs.lint-result }}'
